lblod/frontend-form-builder

- app/components/input-types-list.js
- app/components/input-types-list/item.js
- app/components/playground.js
- app/controllers/codelijsten.js
- app/controllers/user-tests/edit.js
- app/controllers/user-tests/new.js
- app/models/file.js
- app/models/generated-form.js
- app/models/user-test.js
- app/router.js
- app/routes/application.js
- app/routes/codelijsten.js
- app/routes/formbuilder/index.js
- app/routes/formbuilder/new.js
- app/routes/user-tests/edit.js
- app/routes/user-tests/index.js
- app/routes/user-tests/new.js
- app/serializers/application.js
- app/services/database.js
- app/services/meta-data-extractor.js
- app/services/semantic-form.js
- app/util/basic-form-template.js
- config/deploy.js
- ember-cli-build.js
- tests/integration/components/input-types-list-test.js
- tests/unit/routes/codelijsten-test.js
- tests/unit/routes/formbuilder-test.js
> Run Prettier on the .js files

- app/components/input-types-list.js
- app/components/input-types-list/item.js
- app/components/playground.hbs
- app/models/generated-form.js
- app/models/user-test.js
- app/routes/application.js
- app/routes/index.js
- app/routes/user-tests/index.js
- app/serializers/application.js
- app/templates/codelijsten.hbs
- app/templates/index.hbs
This resolves most linting errors (or ignores / converts them into a warning where appropriate).
> Fix linting errors

- app/components/input-types-list.hbs
- app/components/input-types-list/item.hbs
- app/styles/_shame.scss
- app/styles/app.scss
- app/styles/project/_c-playground.scss
- app/templates/application.hbs
- app/templates/formbuilder/edit.hbs
- app/templates/index.hbs
- app/templates/user-tests/edit.hbs
- app/templates/user-tests/index.hbs
- ember-cli-build.js
- package.json
These are mostly internal changes, but it does include a visual update so it could be considered a feature.
> Update to Appuniversum v1.8.0

- app/helpers/format-date-time.js
- app/helpers/format-date.js
- app/templates/index.hbs
- app/templates/user-tests/index.hbs
- package.json
- tests/integration/helpers/format-date-test.js
- tests/integration/helpers/format-date-time-test.js
This replaces ember-moment with 2 custom helpers.
> Remove ember-moment

- app/components/toolbar.hbs
- app/components/toolbar.js
- app/templates/application.hbs
- app/templates/user-tests/edit.hbs
- ember-cli-build.js
The remaining deprecations come from the form-fields addon.
> Resolve Appuniversum deprecations

- app/components/toolbar.hbs
- app/components/toolbar.js
- package-lock.json
- package.json
This fixes the remaining Appuniversum deprecations.
> Resolve all Appuniversum v2.15 deprecations

- app/components/add-validations-to-form.js
This is already fixing the loading issue
> Fix: data is not loaded in builder form when switching between tabs

- app/components/add-validations-to-form.hbs
- app/components/add-validations-to-form.js
- app/components/rdf-form-fields/validation-concept-scheme-selector.js
- app/controllers/formbuilder/edit.js
- app/templates/formbuilder/edit.hbs
- app/utils/add-field-valdiations-to-formNodesL.js
- app/utils/create-store-for-field.js
- app/utils/forking-store-helpers.js
- app/utils/get-field-and-validation-triples.js
- app/utils/get-triples-per-field-in-store.js
- app/utils/merge-field-data-with-builder-form.js
- app/utils/rdflib.js
- app/utils/remove-unassigned-nodes-from-graph.js
- app/utils/toaster-message-helper.js
- app/utils/validation-form-templates/template-prefixes.js
- app/utils/validation-form-templates/template.js
- app/utils/validation-helpers.js
- app/utils/validation-shape-validators.js
- public/forms/validation/form.ttl
> feat: valdiation form will create a separate form for each field

- app/components/code-edit-modal.hbs
- app/components/code-edit-modal.js
- app/components/toolbar.hbs
- app/controllers/formbuilder/edit.js
- app/modifiers/editor.js
- app/routes/formbuilder/edit.js
- app/templates/formbuilder/edit.hbs
- app/templates/index.hbs
This refactors the setup code so it's more flexible and easier to follow.
It's still rough and not very well tested, so most likely incomplete,  but I won't be able to finish for a while..
> Refactor the "refresh" task

- app/components/toolbar.js
- app/controllers/formbuilder/edit.js
- app/services/form-code-manager.js
- app/utils/basic-form-template.js
- tests/unit/services/form-code-manager-test.js
SFB-46](https://binnenland.atlassian.net/browse/SFB-46)
When switching between tabs or updating the code the formChanged variable is not updated correctly.  
In this PR im creating a service that will keep track of the version of the ttl code. Every time the code is saved the reference is move to the latest ttl code. Every change made from there on will be compared with the reference.
1. Change the builder form or validation form so the preview screen  is updated. See if the `formChanged` is correct.
2. Go back to the original state of the form manually and see if `formChanged` is back to `false`
-  https://binnenland.atlassian.net/browse/SFB-43
> feat: form is changed needs an upgrade

- config/environment.js
- package-lock.json
- package.json
[SFB-81](https://binnenland.atlassian.net/browse/SFB-81)
This PR  will make it possible to use feature flags for the application. Example in the future we want a `codelijsten` in the application but we do not want to show it yet on our online application.
Go to `config/environment.js` and change the boolean under `featureFlags` to false. now you will see that the builder/validation switch will appear or dissappear.
- /
> SFB-81: Implement feature flags

- app/components/add-validations-to-form.hbs
- app/components/add-validations-to-form.js
- app/utils/create-field-data-for-subject.js
- app/utils/get-triples-per-field-in-store.js
- app/utils/validation/add-field-valdiations-to-formNodesL.js
[SFB-85](https://binnenland.atlassian.net/browse/SFB-85)
When selecting a field in the validations tab the data is not always loaded. Now the data is created when selecting a field which means the data should always bet there when asked for.
Open the validation tab and start switching between fields and while doing so add and remove some validations.
- /
> SFB-85: validations form data not always shown

- app/components/rdf-form-fields/validation-concept-scheme-selector.js
- app/controllers/formbuilder/edit/configuration.js
- app/utils/forking-store-helpers.js
Some methods in the helper where not used and some could be moved to the parent component so that's what I did :D
> refactor: forkingstore helpers

- app/components/rdf-form-fields/validation-concept-scheme-selector.hbs
- app/components/rdf-form-fields/validation-concept-scheme-selector.js
- app/utils/validation/get-default-error-message-for-validation.js
- public/forms/validation/form.ttl
SFB-68 
Adding default error messages to the validation tab
> SFB-68 improving the error message of validations

- app/components/rdf-form-fields/validation-concept-scheme-selector.js
- config/environment.js
- public/forms/validation/form.ttl
DL-0001
Please include a summary of the change and which issue is fixed. Please also include context.
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
- http://github.com/PR/2314135
> feature flag on default error message

- package-lock.json
Got the warning in the woodpecker build file so i updated it. See if it does not break anything
> bump: caniuse-lite 1.0.30001579

- app/components/rdf-form-fields/property-group-selector.js
- app/utils/ttl-templates/basic-form-template.js
- package-lock.json
- package.json
- public/forms/builder/form.ttl
SFB 132
Changing the builder tab so it supports and creates V2 forms
try making/editing V2 forms in the builder tab (no configuration or validations yet)
> SFB-132/visual builder to v2

- app/components/rdf-form-fields/property-group-selector.js
- app/controllers/formbuilder/edit/configuration.js
- app/utils/ttl-templates/basic-form-template.js
- package-lock.json
- package.json
- public/forms/builder/form.ttl
SFB-148
Make it possible to edit configuration of a field
> SFB-148: config tab to v2

- app/components/field-validations-form.js
- app/components/rdf-form-fields/property-group-selector.js
- app/utils/clean-up-ttl/remove-all-duplicate-validations.js
- app/utils/forking-store-helpers.js
- app/utils/ttl-templates/basic-form-template.js
- app/utils/ttl-templates/field-validation-template.js
- app/utils/validation/add-field-valdiations-to-formNodesL.js
- app/utils/validation/are-validations-in-graph-validated.js
- package-lock.json
- package.json
- public/forms/builder/form.ttl
- public/forms/validation/form.ttl
- tests/unit/utils/clean-up-ttl/resources/basic-form-with-duplicate-validation-on-field-result.js
- tests/unit/utils/clean-up-ttl/resources/basic-form-with-duplicate-validation-on-field.js
- tests/unit/utils/clean-up-ttl/resources/basic-form-with-one-validation-on-field.js
- tests/unit/utils/clean-up-ttl/resources/basic-form-without-validations.js
SFB147
After updating to V2 forms we need the validations tab to be updated
> SFB147: v2 cant edit validations in validation tab

- app/components/field-validations-form.js
- app/components/rdf-form-fields/property-group-selector.js
- app/controllers/formbuilder/edit/configuration.js
- app/utils/clean-up-ttl/remove-all-duplicate-validations.js
- app/utils/code-editor/completion/section/form-predicates.js
- app/utils/code-editor/completion/section/form-types.js
- app/utils/code-editor/completion/section/sh-predicates.js
- app/utils/code-editor/format/rules/format-blankNode-validations.js
- app/utils/forking-store-helpers.js
- app/utils/ttl-templates/basic-form-template.js
- app/utils/ttl-templates/field-validation-template.js
- app/utils/validation/add-field-valdiations-to-formNodesL.js
- app/utils/validation/are-validations-in-graph-validated.js
- package-lock.json
- package.json
- public/forms/builder/form.ttl
- public/forms/validation/form.ttl
- tests/unit/utils/clean-up-ttl/resources/basic-form-with-duplicate-validation-on-field-result.js
- tests/unit/utils/clean-up-ttl/resources/basic-form-with-duplicate-validation-on-field.js
- tests/unit/utils/clean-up-ttl/resources/basic-form-with-one-validation-on-field.js
- tests/unit/utils/clean-up-ttl/resources/basic-form-without-validations.js
- tests/unit/utils/clean-up-ttl/resources/remove-unreferenced-subjects/basic-form-with-unreferenced-field.js
- tests/unit/utils/clean-up-ttl/resources/remove-unreferenced-subjects/basic-form.js
SFB-131
This uses the newer version of ESFF that uses the newer V2 form model
For now you can only preview V2 forms.
> change ESFF version that uses V2 model

- app/components/toolbar.js
- app/controllers/codelijsten/edit.js
- app/models/concept-scheme.js
- app/router.js
- app/routes/codelijsten/new.js
- app/templates/codelijsten/edit.hbs
- app/utils/constants.js
- config/environment.js
- translations/codelists/en-us.yaml
- translations/codelists/nl-be.yaml
- translations/messages/en-us.yaml
- translations/messages/nl-be.yaml
[SFB-140](https://binnenland.atlassian.net/browse/SFB-140)
A concept scheme has no description. To make the user understand what it represents we are adding an extra field where they can specify for what this codelist can be used for.
**NOTE:** Also made a change in the [app-form-builder](https://github.com/lblod/app-form-builder/commit/fb3f3f67413a1b825065953b509f9e1eebb86336)
1. Can fill in a description for a custom codelist
2. Cannot leave it empty
3. The added description is visible when opening it
4. When opening a private codelist like `BeleidsDomeinCode` it just shows the text as a paragraph
- /
> SFB-140: concept scheme description

- app/utils/SHACL/shacl-validate-ttl-code.js
- app/utils/shacl-validate-ttl-code.js
- package-lock.json
- package.json
- tests/unit/SHACL/V2/field-test.js
- tests/unit/SHACL/V2/max-characters-constraint-test.js
- tests/unit/SHACL/V2/required-constraint.js
[SFB-142](https://binnenland.atlassian.net/browse/SFB-142)
Alot of ttl code is generated with the form-builder. This code is not validated yet. Validations are checked with custom methods if they contain all the correct properties to add the validation but that is it.
Create `nodeShapes` for all the items in the formTtl for `V2 forms`: 
* field
* section
* required constraint
* max characters constraint
See if the SHACL shape test are passing and if I didn't miss a test.
- /
> SFB-142: validator method for shacl shapes

- app/controllers/formbuilder/edit.js
- app/controllers/forms/test.js
- app/router.js
- app/routes/forms/test.js
- app/styles/app.scss
- app/styles/project/c-form-test.scss
- app/templates/codelijsten/edit.hbs
- app/templates/codelijsten/index.hbs
- app/templates/forms/test.hbs
- app/templates/index.hbs
- app/utils/find-ttl-for-used-concept-schemes.js
- translations/main/en-us.yaml
- translations/main/nl-be.yaml
- translations/messages/en-us.yaml
- translations/messages/nl-be.yaml
[SFB-172](https://binnenland.atlassian.net/browse/SFB-172)
Improve the test page of a form. I created a new route for this as I do not know what the user-test page contains of functionality. _forms/:id/test'_ will be the route to go to if you want to test the form.
1. Press the "Voorbeeld" button in the form overview, you should route to _forms/:id/test_
2. An example of the generated form will be shown. Almost identically to the preview form in the formbuilder edit route
> SFB-172: create form test page

- app/components/toolbar.hbs
- app/controllers/codelijsten/index.js
- app/routes/codelijsten/index.js
- app/routes/formbuilder/edit.js
- app/templates/codelijsten/index.hbs
- translations/main/en-us.yaml
- translations/main/nl-be.yaml
SFB-165
using the a service to pass and hold the id was not ideal so doing it the right way now
- https://github.com/lblod/frontend-form-builder/pull/121
> SFB-165: using query parameters to pass the form id to codelijsten index

- app/components/rdf-form-fields/aggregate-field.hbs
- app/components/rdf-form-fields/aggregate-field.js
- app/routes/formbuilder/edit.js
- app/utils/code-editor/completion/section/display-types.js
- public/SHACL/V2/field.ttl
- public/forms/builder/meta.ttl
[SFB-179](https://binnenland.atlassian.net/browse/SFB-179)
Create a custom component that can calculate the sum of all values in a table column. These values will point to the `Aggregate field` by setting the scope and path on the column and field
1. Can select the aggregate field component in the builder ('Som van tabel kolom')
2. Will show a new field in the form
3. After setting all the info you the total sum is calculated when a new field is added to the column (info can be found on how to do this in the linked PR's)
- https://github.com/lblod/frontend-form-builder/pull/119
- https://github.com/lblod/frontend-form-builder/pull/127
> SFB-179: Aggregate field

- app/components/toolbar.hbs
- app/controllers/codelijsten/index.js
- app/routes/codelijsten/index.js
- app/styles/app.scss
- app/styles/project/_c-app-codelijsten.scss
- app/templates/codelijsten/index.hbs
- translations/codelists/en-us.yaml
- translations/codelists/nl-be.yaml
[SFB-193](https://binnenland.atlassian.net/browse/SFB-193)
As a user I want to search my codelist by name. this is done by using the `mu-cl resource` filters.
1. go to the codelist overview
2. a search input should be visible
3. when typing in the search input the data will update to the requested values
- /
> SFB-193: add the search input field to the codelist overview

- app/components/concept-scheme-uri-selector.hbs
- app/controllers/formbuilder/edit/configuration.js
- app/templates/formbuilder/edit/configuration.hbs
- app/utils/forking-store-helpers.js
- translations/messages/en-us.yaml
- translations/messages/nl-be.yaml
[SFB-155](https://binnenland.atlassian.net/browse/SFB-155)
Show the path value of the field in the configuration tab.
**Default paths**
**Complex path**
Is the specified path in the ttl code visible in the configuration tab.
- /
> SFB-155 :awareness of field path

- app/components/add-validations-to-form.hbs
- app/components/toolbar.hbs
- app/index.html
- app/styles/_shame.scss
- app/styles/project/c-form-builder-edit.scss
- app/styles/project/c-semantic-data.scss
- app/templates/application.hbs
- app/templates/codelijsten/edit.hbs
- app/templates/codelijsten/index.hbs
- app/templates/formbuilder/edit.hbs
- app/templates/formbuilder/edit/builder.hbs
- app/templates/formbuilder/edit/configuration.hbs
- app/templates/formbuilder/edit/semantic-data.hbs
- app/templates/formbuilder/edit/validations.hbs
- app/templates/index.hbs
- translations/main/en-us.yaml
- translations/main/nl-be.yaml
SFB-208
Rebrand to gelinkte formulieren + general styling improvements
> Rebrand to gelinkte formulieren + general styling improvements

- app/controllers/formbuilder/edit/code.js
- app/styles/app.scss
- app/styles/project/c-code-edit-console.scss
- app/templates/formbuilder/edit/code.hbs
- translations/main/en-us.yaml
- translations/main/nl-be.yaml
SFB 186
SHACL messages will be logged in the console
> SFB 186: add shacl messages to console

- app/controllers/formbuilder/edit/code.js
- app/styles/app.scss
- app/styles/project/c-code-edit-console.scss
- app/templates/formbuilder/edit/code.hbs
- translations/main/en-us.yaml
- translations/main/nl-be.yaml
SFB-185
This pr will cover the start of the console for the code editor, it will not have actual errors and warnings yet. this will be done in the next pr.
> SFB-185: Implmentation of a console in the code tab

- app/controllers/formbuilder/edit/code.js
- app/styles/project/c-code-edit-console.scss
- app/templates/formbuilder/edit/code.hbs
- app/utils/SHACL/format-shacl-validation-report.js
- app/utils/constants.js
- public/SHACL/V2/field.ttl
- public/SHACL/V2/section.ttl
- translations/messages/en-us.yaml
- translations/messages/nl-be.yaml
[SFB-213](https://binnenland.atlassian.net/browse/SFB-213)
When updatin gthe ttl code is often brekas the application so you cannot do anything anymore. To fix this im checking if the shacl shapes are returning any errors.
Also update the console messages to show errors and warnings differently.
1. Open the console it should display a difference between a warning and an error
2. Change the display type of a field. It will not update the preview as it is not valid
3. The check if there are shacl errors is only done for the code editor as this is the place where users can freely edit the ttl code
- /
> SFB-213: Ttl code that has shacl errors is not passed on

- app/components/rdf-form-fields/error-message-input-field.hbs
- app/components/rdf-form-fields/error-message-input-field.js
- app/components/rdf-form-fields/validation-concept-scheme-selector.js
- public/forms/validation/form.ttl
SFB-214
The default message is automatically added when adding a validation to field, if you want to change the message you can check a box and a input field will appear. 
Add validation and check messages.
> SFB-214/Make custom validation message optional

- app/components/rdf-form-fields/begrotingstabel-total-field.hbs
- app/components/rdf-form-fields/begrotingstabel-total-field.js
- app/routes/formbuilder/new.js
- public/forms/templates/begrotingstabel.ttl
[SFB-218](https://binnenland.atlassian.net/browse/SFB-218)
We want to calculate the sum of values in a column. These values will be shown in a total field. There will be added more fields depending on how many targets you add to the begrotingsTotal field. These values will be shown in the form preview. When these values do not end up being equal to each other we will show a message that it is not valid.
1. Create a new form from template. Choose `Begrotingstabel`
2. Start adding values to the `Inkomsten` and `Uitgaven` tables
3. If the result values do not match each other a error message is shown
- https://github.com/lblod/frontend-form-builder/pull/144
**V1**
**V2**
**V3**
> SFB-218: logic begrotingstabel total field

- app/components/concept-scheme-uri-selector.hbs
- app/components/configuration/table.hbs
- app/components/configuration/table.js
- app/controllers/formbuilder/edit/configuration.js
- app/templates/formbuilder/edit/configuration.hbs
- public/forms/templates/basic-table.ttl
- translations/main/en-us.yaml
- translations/main/nl-be.yaml
- translations/messages/en-us.yaml
- translations/messages/nl-be.yaml
[SFB-212](https://binnenland.atlassian.net/browse/SFB-212)
We want to show the config table card to show for every tbale that is in the selected section.
Will see multiple table configs for every table in the section
- https://github.com/lblod/frontend-form-builder/pull/141
> SFB- 212/table config card for multiple tables in section

- app/utils/SHACL/shacl-validate-ttl-code.js
- public/SHACL/V2/valid-phone-number-constraint.ttl
- tests/unit/SHACL/V2/valid-phone-number-constraint-test.js
[SFB-235](https://binnenland.atlassian.net/browse/SFB-235)
A shape for validation "Valid phone number" was not yet added to the list off shapes. With this PR we add this shape to the list so next time someone uses this validation wrong we get feedback on that.
1. run the test of the exact value constraint
2. Add the validation to your field and try to make break it  by filling in data that is not supposed to be there
- /
> SFB-235: add shape + test for valid phone number constraint
