lblod/frontend-form-builder

.woodpecker/.test.yml
Dockerfile

node 16 has been recently EOLd and we were already using v3 lock files.

Update to node 18

---

package-lock.json
package.json

Redirecting to the overview page from a very large form resulted in the browser freezing for several seconds. The underlying issue is observer system in the forking-store which gets used by the form fields addon. The latest patch fixes that issue upstream, so we update to that version to also fix the issue here.
With this PR leaving the details page of the "Big form" should no longer freeze the browser.

Fix a slow redirect issue

---

README.md
app/components/concept-scheme-uri-selector.js
app/components/toolbar.hbs
ember-cli-build.js
package-lock.json
package.json

Embroider is the new build system for Ember that uses Webpack behind the scenes. This should result in faster (re)builds and smaller bundles without any real code changes.
More information: https://github.com/embroider-build/embroider
(You might need to install Watchman if you get file watching issues during the build)

Enable the Embroider build system

---

app/controllers/formbuilder/edit.js

Everytime you go to the builder tab the refresh method is called with the `isInitialRouteCall` parameter on `true` this makes it that the `formChanged` variable is set to false as when initially lodaing the data there is no way that you already changed something in the form. 
I added a saved state of the variable `formChanged` to overwrite this but it feels that im hAcKinG more than we should @Windvis

Fix: saving the form data

---

package-lock.json
package.json
public/forms/builder/form.ttl

This uses the new reordering feature to the builder form listings.
I didn't add it to the "validations" listing since the order there doesn't really matter _I think_?

Add listing item reordering

---

app/components/rdf-form-fields/validation-concept-scheme-selector.hbs
app/components/rdf-form-fields/validation-concept-scheme-selector.js
app/routes/formbuilder/edit.js
public/forms/builder/meta.ttl
public/forms/validation/form.ttl

Issue: [SFB-3](https://binnenland.atlassian.net/jira/software/c/projects/SFB/issues/SFB-3)
This selector will only show the validations that are possible for that display type (field).
Each field has a predicate `canHaveValidation` and the options of the dropdown are based on that

Feat: create validation concept scheme selector

---

app/components/add-validations-to-form.js

[SFB-40]https://binnenland.atlassian.net/browse/SFB-40
This update does not fall directly under this issue but while checking on how it should work for the result message i got the idea that the component of the validation tab is not updated when something is changed in the field's form. Now when adding a validation the preview is directly updated.
Add a validation to a field so the serialization is triggered.
- /

feat: directly serialize the field forms with the builder form

---

app/components/add-validations-to-form.js

[SFB-44](https://binnenland.atlassian.net/browse/SFB-44)
As we changed that every change in a fields validation form triggers a merging of the field form with the builderForm so the validation will be visible in the preview screen. This throwed an error because the current task for merging was cancelled. (See screenshot in the issue).
As the task is restartable previous task can be cancelled. The issue here was that we are `waiting` in the update of the field form what makes the restartable task obsolete.
Reverted to the commit where the valdiations where only applied when the switch was toggled. Wokring from there on to improve the way it works.
1. Create a form with one field and add multiple validations to it
2. Create a form with a second field and see if the validations added to the …

Refactor: merging of the field forms

---

app/components/code-edit-modal.hbs
app/components/code-edit-modal.js
app/components/toolbar.hbs
app/components/toolbar.js
app/controllers/formbuilder/edit.js
app/services/form-code-manager.js

[SFB-46](https://binnenland.atlassian.net/browse/SFB-46)
Editing the code in the code editor is atm not workable. In this PR you can find that two buttons are added to reset the code to the previous state or save the current code. 
The big change here is that the code is only updated to the preview and the builder if you press the save button. 
Not a fan of:
* ~when pressing save the editor closes (this is intentionally) => cannot update the this.args.code of the component or should rerender it fully~
* ~When you go directly to the editor without changing anything the code you will see is the `basic-form-template` with the comments. But when you change something in that form, save it and than open the editor again it still shows the code that represents the output but now it is optimized …

SFB-46: make the code editor workable

---

app/controllers/formbuilder/edit.js
app/controllers/formbuilder/edit/code.js
app/controllers/formbuilder/edit/validations.js
app/routes/formbuilder/edit/builder.js
app/routes/formbuilder/edit/code.js
app/templates/formbuilder/edit.hbs
app/templates/formbuilder/edit/builder.hbs
app/templates/formbuilder/edit/code.hbs
app/templates/formbuilder/edit/validations.hbs

[SFB-82](https://binnenland.atlassian.net/browse/SFB-82)
In the navigation at the top are three routes defined. Each route has ts own preview rdf-form and this should'nt be the case. We will be moving this rdf-form to the parent `edit` template so it is common and we do not have duplicate code that will render the preview form.
Everything should work as before. In the code there should only be one `rdf-form` with a `previewStore`
- /

SFB-82: Duplicate preview form in each route template

---

app/components/rdf-form-fields/country-code-concept-scheme-selector.js
app/utils/validation/are-validations-in-graph-validated.js
app/utils/validation/shape-validators/is-country-code-added.js
public/forms/validation/form.ttl

[SFB-93](https://binnenland.atlassian.net/browse/SFB-93)
When adding the phone number validation to a field it was not fully applied to that field. This is because the component sets the default value when none is selected but this is never added to the store when you do not change this value. When you do change the value with the dropdown the validation was added.
The missing part `form:defaultCountry "BE"` was not in the triples of the validation. Now the dropdown is required and checked before applying that change.
Add a field to the form and apply the phone number validation to it. 
1. Do not select a country code and leave
2. Select a country code and leave
3. See result
- /

SFB-93: make the country code mandatory to fill in

---

app/components/concept-scheme-uri-selector.hbs
app/components/concept-scheme-uri-selector.js
app/controllers/codelijsten.js
app/models/concept-scheme.js
app/models/concept.js
app/styles/project/_c-playground.scss
app/templates/codelijsten.hbs
tests/unit/models/concept-scheme-test.js
tests/unit/models/concept-test.js

[SFB-100](https://binnenland.atlassian.net/browse/SFB-100)
The concept schemes are fetched with a direct sparql query in the frontend. Change this by getting the concept-schemes with their concepts to be get from the store `this.store.query('concept-scheme')`
Checkout the app for the frontend on the the `SFB-100` branch. Make sure all the migrations have run.
Check the code if the `concept-scheme-uri-selector` is using the store instead of a direct sparql query. All options should be visible with their concepts on the left side.
- https://github.com/lblod/app-form-builder/pull/7

SFB-100: create concept-scheme and concept model from store instead of direct sparql

---

app/templates/index.hbs

[SFB-114](https://binnenland.atlassian.net/browse/SFB-114)
Remove the action `bewerk` and make the name clickable to go to the edit page of the form.
- Make sure it is possible to go to the edit page of the form.
- Bewerk action is removed

SFB-114: remove the bewerk column + make the name clickable 

---

app/styles/_shame.scss
app/templates/index.hbs

Following https://www.figma.com/file/iwxgR1dVYjIX4AknHe57eH/formbuilder-smallUXchanges?type=design&node-id=0-1&mode=design&t=4b479qUGfDJFqfHY-0
1. Switch form actions to `preview` and `verwijder` 
2. ~Remove the borders in the table~

Form overview style updates

---

app/components/toolbar.hbs
app/components/toolbar.js
app/styles/project/_c-app-chrome.scss

[SFB-116](https://binnenland.atlassian.net/browse/SFB-116)
The action to edit the name of a form is hidden behind the `formulier acties` dropdown. Add a pencil icon next to the Title and let it open the edit name and description modal.
1. Click the `formulier acties` dropdown => the option to edit should be removed
2. Click on the pencil icon next to the title of the form and see if the modal opens
3. Change the name see if it updates
- /

SFB-116: add pencil icon next to title that opens the edit form name

---

app/components/toolbar.hbs
app/styles/app.scss
app/styles/project/_c-app-toolbar.scss

[SFB-117](https://binnenland.atlassian.net/browse/SFB-117)
The form options are not used that much move the to a split button next to safe.

refactor: create split button for form actions and safe

---

app/components/create-form-modal.hbs
app/components/create-form-modal.js
app/components/toolbar.hbs
app/components/toolbar.js
app/styles/project/_c-app-chrome.scss
app/styles/project/c-form-builder-edit.scss
app/templates/index.hbs
app/utils/constants.js

[SFB-103](https://binnenland.atlassian.net/browse/SFB-103)
The description is not used when a form is created so this can be removed. When filling in a name for the form the amount of characters is infinite. Let's limit it to 120 characters.
When your form is created and you want to edit the name it pops up a modal for editing the name. As the description is removed when can directly edit the name in the toolbar.
1. Create a new form test the limits of the input field
2. When the form is created edit the name of the form in the toolbar 
- /

SFB-103: character limit for name of form + edit name

---

app/components/add-validations-to-form.js
app/components/rdf-form-fields/validation-concept-scheme-selector.js
app/controllers/formbuilder/edit.js
app/controllers/formbuilder/edit/validations.js
app/utils/clean-up-ttl/remove-all-duplicate-validations.js
app/utils/forking-store-helpers.js
tests/unit/utils/clean-up-ttl/remove-all-duplicate-validations-test.js
tests/unit/utils/clean-up-ttl/resources/basic-form-with-duplicate-validation-on-field-result.js
tests/unit/utils/clean-up-ttl/resources/basic-form-with-duplicate-validation-on-field.js
tests/unit/utils/clean-up-ttl/resources/basic-form-with-one-validation-on-field.js
tests/unit/utils/clean-up-ttl/resources/basic-form-without-validations.js

[SFB-113](https://binnenland.atlassian.net/browse/SFB-113)
Whit the latest refactor of the validations it is possible to add duplicate validations to a field. This is only possible when adding the duplicate validation right behind each other. This means that you do not leave the `validations` tab when doing this. When you switch tabs and try to add a duplicate the components are aware and than this is not possible anymore.
In this PR I created a method that will clean up any duplicate validations from the ttl code. I also tested this method so we can be more sure that this is working as expected.
This PR does not fix the possibility to add a duplicate validation in the same active tab!
1. Go to the validations tab and add two validations of the same type
2. When going back to the code …

SFB-113: Clean up of duplicate validations in the code

---

app/controllers/formbuilder/edit/code.js
app/controllers/formbuilder/edit/configuration.js
app/helpers/is-display-type-with-options.js
app/utils/can-display-type-have-form-options.js
app/utils/clean-up-ttl/clean-up-field-options.js
app/utils/clean-up-ttl/clean-up-ttl-code.js

[SFB-121](https://binnenland.atlassian.net/browse/SFB-121)
When adding a codelist to a field the data is updated that the field will have form:options. These options remained when switching the displayType to a not selector displayType. Now when people go to the code editor the field options are cleanedup.
1. Create a field with a selector displayType
2. Add options to the selector
3. Go to the builder tab and change the displayType to defaultInput for example
4. Go to the code editor and see if the conceptscheme option is still available on the form:options
- /

SFB-121: Remove the form:options if the field displayType does not support it

---

app/router.js
app/templates/codelijsten/index.hbs
config/environment.js

Users can make their own codelists but those itemst will not be visible in the dropdown when they want to assign a codelist to a field. 
Put the create button behind a feature flag `CAN_CREATE_OWN_CODELIST` and set it to `false`.
- Can you create a new codelists?

feat: add feature flag for create codelist button

---

app/components/concept-scheme-uri-selector.js
app/components/rdf-form-fields/country-code-concept-scheme-selector.js
app/components/rdf-form-fields/property-group-selector.js
app/components/rdf-form-fields/validation-concept-scheme-selector.js
app/utils/sort-object-on-property.js
tests/unit/utils/sort-object-on-property-test.js

In many files  a sorting method is created at the top of the file. This method was the same for a lot of files. Since we created a `sort objects on property` util method we can use that one so we do not have to redefine the `byLabel` method in each file.
```js
function byLabel(a, b) {
const textA = a.label.toUpperCase();
const textB = b.label.toUpperCase();
return textA < textB ? -1 : textA > textB ? 1 : 0;
}
```
1. all items should be sorted ascernding
2. except for the validation type options I hyave set these on descending so the "Verplicht" options what is used the most is at the top of the list
3. Created a basic unit test that will show that we can sort on property `label` _ascending_ and _descending_.

Refactor: duplicate methods for sorting

---

app/components/toolbar.js
app/controllers/index.js
app/routes/formbuilder/edit.js
app/services/form-code-manager.js
translations/messages/en-us.yaml
translations/messages/nl-be.yaml

[SFB-151](https://binnenland.atlassian.net/browse/SFB-151)
When updating the form and than deleting it without saving the a modal is shown after that you confirmed to delete the form. This modal should not be shown when the form is already delete.
- [x ] Bug fix
1. Create a form and change something in the ttl code
2. Go to the split button and delete the form
3. Cancel the deletion => the form should be in the same state as before and you did not see any modal for unsaved changes
4. Press the delete button again and confirm that you want to delete it. The unsaved changes modal is not shown and a toaster is provided that the form is successfully deleted
- /

SFB-151: bug fix unsaved changes modal on delete

---

app/controllers/formbuilder/edit.js
app/services/form-version.js
tests/unit/services/form-version-test.js
tests/unit/services/resources/version-one-and-two-combination-form.js
tests/unit/services/resources/version-one-form.js
tests/unit/services/resources/version-two-form.js

[SFB-125](https://binnenland.atlassian.net/browse/SFB-125)
Before we can show a message that the user is editing a V1 form the check of the version needs to happen first. 
I did not make use of the violations of the shacl shape validation as the way it is implemented now feels easier to maintain, understand and use in the code.
1. all test should be green
2. a console log with the version should be visible
3. depending on what version of form you are using it should display the correct one
- https://github.com/lblod/frontend-form-builder/pull/115

SFB-125: check version of ttl code

---

app/controllers/formbuilder/edit.js
app/helpers/is-equal.js
app/templates/formbuilder/edit.hbs
translations/messages/en-us.yaml
translations/messages/nl-be.yaml

[SFB-125](https://binnenland.atlassian.net/browse/SFB-125)
Showing an alert when the version of the form is a V1 form. Added a translation for this so it can easely be changed if we want. This banner will be shown above the navigation tabs in the edit route.
1. Open a V1 form => alert shows
2. Open a V2 form => no alert
3. Edit a V1 or V2 form => the alert will only show when you have a full V1 or V2 form not a combination
- https://github.com/lblod/frontend-form-builder/pull/114

SFB-125: extend show message on v1 form

---

app/components/rdf-form-fields/error-message-input-field.hbs
app/components/rdf-form-fields/error-message-input-field.js
app/components/rdf-form-fields/validation-concept-scheme-selector.js
app/routes/formbuilder/edit.js
config/environment.js
package-lock.json
public/forms/validation/form.ttl

SFB-122
It is possible to add multiple error messages to a validation, this shouldn't be possible. Fixed the double error messages by making a custom rdf form field. This input field will remove the previous error message when making a new one.
1) choose a validation type
2) Click in the input field, the default error message will show (if there is one of course) or type a custom one
3) try changing validation type
4) if you want the default error message of that validation type remove the old one and just click out of the input field or again type custom one

SFB-122:double error messages

---

app/components/toolbar.js
app/controllers/codelijsten/edit.js
app/templates/codelijsten/edit.hbs
app/utils/download-text-as-file.js
translations/codelists/en-us.yaml
translations/codelists/nl-be.yaml

[SFB-156](https://binnenland.atlassian.net/browse/SFB-156)
When users make their own codelists they can only see this list in the codelist details page or in the preview form when creating a form. Of course they also want the information from the codelist in their application. We add an extra option to the split button in the detail view so users can export the code code as a ttl file.
1. create/go to a custom codelist
2. Press the split button and donwload the file.
3. When opening the file the content of the codelist should be in there
4. As the toolbar also uses the same new download method try and export the ttl code of a form 
- /

SFB-156: export custom codelist

---

app/templates/user-tests/edit.hbs

[SFB-102](https://binnenland.atlassian.net/browse/SFB-102)
A ticket from the testers: it is strange that you go to the user-test overview page when clicking back in the user-test detail screen, This because there are no other actions in the user-test overview screen to do than. This is a double click back that is not needed. 
Update the route and text of the button to go to the forms overview page.
1. forms overview, select a `voorbeeld` of a form
2. Press the top right `terug naar formulieren` 
3. It should send you back to the forms overview instead of the user-test overview
- /

SFB-102: skip test form overview

---

app/components/toolbar.hbs
app/templates/codelijsten/edit.hbs
app/templates/codelijsten/index.hbs
translations/codelists/en-us.yaml
translations/codelists/nl-be.yaml
translations/main/en-us.yaml
translations/main/nl-be.yaml

[SFB-174](https://binnenland.atlassian.net/browse/SFB-174)
The breadcrumsbar looks off. Update the bar to look the same as in [appuniversum breadcrums](https://appuniversum.github.io/ember-appuniversum/?path=/story/templates-app-with-breadcrumbs--page) 
Also remove the _Bewaard op ..._ text in the toolbar.
1. Is the _Bewaard op .._ text still visible in the toolbar? 
2. Design of the breadcrums bar is the same as in the appuniversum addon
- /

SFB-174: Update the breadcrums bar 

---

app/components/concept-scheme-uri-selector.js
app/controllers/codelijsten/edit.js
app/models/concept-scheme.js
app/templates/codelijsten/edit.hbs
app/templates/codelijsten/index.hbs
translations/codelists/en-us.yaml
translations/codelists/nl-be.yaml
translations/main/en-us.yaml
translations/main/nl-be.yaml
translations/messages/en-us.yaml
translations/messages/nl-be.yaml

[SFB-168](https://binnenland.atlassian.net/browse/SFB-168)
Users can create custom codelists now. As other users can also make use of these codelists it's better to archive the codelists that to delete it. This makes it possible to restore the codelist if we want to.
1. Create a codelist
2. Archive the codelist
3. You should see the archived codelist in the overview list but with a new tag "Ge-archiveerd"
4. When opening the archived list you will only be able to view the codelist
-  https://github.com/lblod/app-form-builder/pull/9

SFB-168:  Archive custom codelists

---

app/services/form-code-manager.js
tests/unit/services/form-code-manager-test.js

[SFB-220](https://binnenland.atlassian.net/browse/SFB-220)
While looking for a good test strategy I found out that the form code manager what is used as a main service in the form builder for keeping track of form ttl changes is not tested yet. In this PR you can find the tests for the  service
Run the ember test. command: `ember test --server --filter="Unit | Service | form-code-manager"`
- /

SFB-220: test form code manager service

---

public/SHACL/V2/max-characters-constraint.ttl
public/SHACL/V2/repositories.ttl
public/SHACL/V2/required-constraint.ttl

SFB-231
When adding a resultMessage to a validation it gave a wrong warning.
If you add 1 string or langString it shouldn't give a warning. If you add more than 1 or the wrong datatype it will give a warning.

SFB-231: fix shacl warning on resultMessage

---

app/utils/SHACL/shacl-validate-ttl-code.js
public/SHACL/V2/positive-number-constraint.ttl
tests/unit/SHACL/V2/positive-number-constraint-test.js

[SFB-233](https://binnenland.atlassian.net/browse/SFB-233)
A shape for validaiton "Positive number" was not yet added to the list off shapes. With this PR we add this shape to the list so next time someone uses this validation wrong we get feedback on that
1. run the test of the positive-number-constraint
2. Add the valdiation to your field and try to make break it  by filling in data that is not supposed to be there
- /

SFB-233: positive number constraint shacl shape

---

app/utils/SHACL/shacl-validate-ttl-code.js
public/SHACL/V2/exact-value-constraint.ttl
tests/unit/SHACL/V2/exact-value-constraint-test.js

[SFB-234](https://binnenland.atlassian.net/browse/SFB-234)
A shape for validaiton "Exact value constraint" was not yet added to the list off shapes. With this PR we add this shape to the list so next time someone uses this validation wrong we get feedback on that.
1. run the test of the exact value constraint
2. Add the validation to your field and try to make break it  by filling in data that is not supposed to be there
- /

SFB-234: add exact value constraint shacl shape

---

app/controllers/codelijsten/edit.js
app/routes/codelijsten/edit.js
app/templates/codelijsten/edit.hbs
app/utils/codelijsten/compare-concept-arrays.js
app/utils/codelijsten/update-concept.js
tests/unit/utils/codelijsten/compare-concept-arrays-test.js

[SFB-242](https://binnenland.atlassian.net/browse/SFB-242)
When routing a away from the `codelijsten.edit` route and the user has unsaved changes the user now has to confirm if they want to save or discard the changes.
The original data is set back to the current view when pressing discard. When pressing the save button it does the same as the current save button.
1. Update a codelist and route back with the arrow in the breadcrumbar
2. A modal will be shown as you did not save your latest changes
3. try out both options
- /

SFB-242: unsaved changed modal when leaving codelijsten.edit

---

app/components/concept-scheme-uri-selector.hbs
app/components/concept-scheme-uri-selector.js
app/utils/constants.js
app/utils/query-all-items-in-store-per-page.js

[SFB-226](https://binnenland.atlassian.net/browse/SFB-226)
When going to the codelists page it returns a 500. The reason is why is unsure yet.
As from the beginning of the concept scheme selector a call was done towards the database to get all the concept schemes in the database. This call was done by adding a parameter `page: { size: 9999 }`. This is not great as if ever the list becomes larger than 9999 it will not show the latest conceptschemes. I updated the call so all the items are get per page. This will make that the amount of calls will increase to get the information, everything will always be get from the database and there is no call anymore that uses a constant of 9999 to get all the items in the store. It does not feel the correct way but it's already better than the …

SFB-226: Remove query with size 999
